//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL.ExcelAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySQL.ExcelAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap action_eer_rev_eng_db {
            get {
                object obj = ResourceManager.GetObject("action_eer_rev_eng_db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chain_link_24x24 {
            get {
                object obj = ResourceManager.GetObject("chain_link_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column has already been mapped, do you want to overwrite existing mapping?.
        /// </summary>
        internal static string ColumnMappedOverwrite {
            get {
                return ResourceManager.GetString("ColumnMappedOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column has already been mapped, do you want to remove it and its mapping?.
        /// </summary>
        internal static string ColumnMappedRemove {
            get {
                return ResourceManager.GetString("ColumnMappedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column mapping for all columns in Excel selection is incomplete. Do you want to proceed with the current mapped data only?.
        /// </summary>
        internal static string ColumnMappingIncomplete {
            get {
                return ResourceManager.GetString("ColumnMappingIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some columns have already been mapped, do you want to overwrite existing mappings?.
        /// </summary>
        internal static string ColumnsMappedOverwrite {
            get {
                return ResourceManager.GetString("ColumnsMappedOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Connection is closed, must be opened first to perform action.
        /// </summary>
        internal static string ConnectionClosedError {
            get {
                return ResourceManager.GetString("ConnectionClosedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbench connections.xml file not found.
        /// </summary>
        internal static string ConnectionsFileNotFound {
            get {
                return ResourceManager.GetString("ConnectionsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open MySQL connection since connection string has not been set.
        /// </summary>
        internal static string ConnectionStringNotSet {
            get {
                return ResourceManager.GetString("ConnectionStringNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current changes will be lost, do you want to continue?.
        /// </summary>
        internal static string CurrentChangesLostConfirmation {
            get {
                return ResourceManager.GetString("CurrentChangesLostConfirmation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap db_Column_16x16 {
            get {
                object obj = ResourceManager.GetObject("db_Column_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_16x16 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_24x24 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_manage_24x24 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_manage_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_manage_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_manage_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_mgmt_Connection_manage_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_mgmt_Connection_manage_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Objects_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_Objects_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Objects_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_Objects_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Routine_16x16 {
            get {
                object obj = ResourceManager.GetObject("db_Routine_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Routine_24x24 {
            get {
                object obj = ResourceManager.GetObject("db_Routine_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Routine_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_Routine_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Routine_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_Routine_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_16x16 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_24x24 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_add_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_add_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_many_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_many_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Schema_many_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_Schema_many_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Table_16x16 {
            get {
                object obj = ResourceManager.GetObject("db_Table_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Table_24x24 {
            get {
                object obj = ResourceManager.GetObject("db_Table_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Table_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_Table_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_Table_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_Table_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_View_16x16 {
            get {
                object obj = ResourceManager.GetObject("db_View_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_View_24x24 {
            get {
                object obj = ResourceManager.GetObject("db_View_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_View_32x32 {
            get {
                object obj = ResourceManager.GetObject("db_View_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_View_48x48 {
            get {
                object obj = ResourceManager.GetObject("db_View_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_data_16x16 {
            get {
                object obj = ResourceManager.GetObject("edit_data_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_data_24x24 {
            get {
                object obj = ResourceManager.GetObject("edit_data_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_data_32x32 {
            get {
                object obj = ResourceManager.GetObject("edit_data_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_data_48x48 {
            get {
                object obj = ResourceManager.GetObject("edit_data_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating a new schema: {0}.
        /// </summary>
        internal static string ErrorCreatingNewSchema {
            get {
                return ResourceManager.GetString("ErrorCreatingNewSchema", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap excel_icon {
            get {
                object obj = ResourceManager.GetObject("excel_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExcelAddinFilter {
            get {
                object obj = ResourceManager.GetObject("ExcelAddinFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon export_excel_existing_table {
            get {
                object obj = ResourceManager.GetObject("export_excel_existing_table", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel_existing_table_16x16 {
            get {
                object obj = ResourceManager.GetObject("export_excel_existing_table_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel_existing_table_32x32 {
            get {
                object obj = ResourceManager.GetObject("export_excel_existing_table_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel_existing_table_48x48 {
            get {
                object obj = ResourceManager.GetObject("export_excel_existing_table_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon export_excel_new_table {
            get {
                object obj = ResourceManager.GetObject("export_excel_new_table", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel_new_table_16x16 {
            get {
                object obj = ResourceManager.GetObject("export_excel_new_table_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel_new_table_32x32 {
            get {
                object obj = ResourceManager.GetObject("export_excel_new_table_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_excel_new_table_48x48 {
            get {
                object obj = ResourceManager.GetObject("export_excel_new_table_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_data_16x16 {
            get {
                object obj = ResourceManager.GetObject("import_data_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_data_32x32 {
            get {
                object obj = ResourceManager.GetObject("import_data_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_data_48x48 {
            get {
                object obj = ResourceManager.GetObject("import_data_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning_16x16 {
            get {
                object obj = ResourceManager.GetObject("lightning_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning_24x24 {
            get {
                object obj = ResourceManager.GetObject("lightning_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning_32x32 {
            get {
                object obj = ResourceManager.GetObject("lightning_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning_48x48 {
            get {
                object obj = ResourceManager.GetObject("lightning_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightning_86x86 {
            get {
                object obj = ResourceManager.GetObject("lightning_86x86", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainLogo {
            get {
                object obj = ResourceManager.GetObject("MainLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon MySQLExcelAddInLogo {
            get {
                object obj = ResourceManager.GetObject("MySQLExcelAddInLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MySQLExcelAddInLogo_16x16 {
            get {
                object obj = ResourceManager.GetObject("MySQLExcelAddInLogo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MySQLExcelAddInLogo_32x32 {
            get {
                object obj = ResourceManager.GetObject("MySQLExcelAddInLogo_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MySQLExcelAddInLogo_48x48 {
            get {
                object obj = ResourceManager.GetObject("MySQLExcelAddInLogo_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MySQLExcelAddInLogo_64x64 {
            get {
                object obj = ResourceManager.GetObject("MySQLExcelAddInLogo_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_connection_16x16 {
            get {
                object obj = ResourceManager.GetObject("new_connection_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_connection_24x24 {
            get {
                object obj = ResourceManager.GetObject("new_connection_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_connection_32x32 {
            get {
                object obj = ResourceManager.GetObject("new_connection_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_connection_48x48 {
            get {
                object obj = ResourceManager.GetObject("new_connection_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected column?.
        /// </summary>
        internal static string RemoveColumnConfirmation {
            get {
                return ResourceManager.GetString("RemoveColumnConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected DB Object used for this action must be of Type =Table..
        /// </summary>
        internal static string SelectedDBObjectNotTable {
            get {
                return ResourceManager.GetString("SelectedDBObjectNotTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty or null DB Object used for this action.  A valid DB Object must be used..
        /// </summary>
        internal static string SelectedDBObjectNull {
            get {
                return ResourceManager.GetString("SelectedDBObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty or null DB Schema used for this action.  A valid Schema must be used..
        /// </summary>
        internal static string SelectedDBSchemaNull {
            get {
                return ResourceManager.GetString("SelectedDBSchemaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty or null Table used for this action.  A valid Table must be used..
        /// </summary>
        internal static string SelectedTableNull {
            get {
                return ResourceManager.GetString("SelectedTableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table must be new in order to create it in MySQL DB..
        /// </summary>
        internal static string TableNotNewInCreate {
            get {
                return ResourceManager.GetString("TableNotNewInCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load databases for the given connection..
        /// </summary>
        internal static string UnableToLoadDatabases {
            get {
                return ResourceManager.GetString("UnableToLoadDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve data from &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToRetrieveData {
            get {
                return ResourceManager.GetString("UnableToRetrieveData", resourceCulture);
            }
        }
    }
}
