//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MySQL.ForExcel.Classes;

namespace MySQL.ForExcel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportDetectDatatype {
            get {
                return ((bool)(this["ExportDetectDatatype"]));
            }
            set {
                this["ExportDetectDatatype"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportAddBufferToVarchar {
            get {
                return ((bool)(this["ExportAddBufferToVarchar"]));
            }
            set {
                this["ExportAddBufferToVarchar"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportAutoIndexIntColumns {
            get {
                return ((bool)(this["ExportAutoIndexIntColumns"]));
            }
            set {
                this["ExportAutoIndexIntColumns"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportAutoAllowEmptyNonIndexColumns {
            get {
                return ((bool)(this["ExportAutoAllowEmptyNonIndexColumns"]));
            }
            set {
                this["ExportAutoAllowEmptyNonIndexColumns"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportUseFormattedValues {
            get {
                return ((bool)(this["ExportUseFormattedValues"]));
            }
            set {
                this["ExportUseFormattedValues"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Append)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppendPerformAutoMap {
            get {
                return ((bool)(this["AppendPerformAutoMap"]));
            }
            set {
                this["AppendPerformAutoMap"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Append)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppendAutoStoreColumnMapping {
            get {
                return ((bool)(this["AppendAutoStoreColumnMapping"]));
            }
            set {
                this["AppendAutoStoreColumnMapping"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Append)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppendReloadColumnMapping {
            get {
                return ((bool)(this["AppendReloadColumnMapping"]));
            }
            set {
                this["AppendReloadColumnMapping"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Append)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppendUseFormattedValues {
            get {
                return ((bool)(this["AppendUseFormattedValues"]));
            }
            set {
                this["AppendUseFormattedValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<MySQL.ForExcel.Classes.MySqlColumnMapping> StoredDataMappings {
            get {
                return ((global::System.Collections.Generic.List<MySQL.ForExcel.Classes.MySqlColumnMapping>)(this["StoredDataMappings"]));
            }
            set {
                this["StoredDataMappings"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ExportLimitPreviewRowsQuantity {
            get {
                return ((int)(this["ExportLimitPreviewRowsQuantity"]));
            }
            set {
                this["ExportLimitPreviewRowsQuantity"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Append)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AppendLimitPreviewRowsQuantity {
            get {
                return ((int)(this["AppendLimitPreviewRowsQuantity"]));
            }
            set {
                this["AppendLimitPreviewRowsQuantity"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public uint GlobalConnectionConnectionTimeout {
            get {
                return ((uint)(this["GlobalConnectionConnectionTimeout"]));
            }
            set {
                this["GlobalConnectionConnectionTimeout"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public uint GlobalConnectionCommandTimeout {
            get {
                return ((uint)(this["GlobalConnectionCommandTimeout"]));
            }
            set {
                this["GlobalConnectionCommandTimeout"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Import)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ImportPreviewRowsQuantity {
            get {
                return ((int)(this["ImportPreviewRowsQuantity"]));
            }
            set {
                this["ImportPreviewRowsQuantity"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Import)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImportEscapeFormulaTextValues {
            get {
                return ((bool)(this["ImportEscapeFormulaTextValues"]));
            }
            set {
                this["ImportEscapeFormulaTextValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertedSettingsStoredMappingsCasing {
            get {
                return ((bool)(this["ConvertedSettingsStoredMappingsCasing"]));
            }
            set {
                this["ConvertedSettingsStoredMappingsCasing"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditUseOptimisticUpdate {
            get {
                return ((bool)(this["EditUseOptimisticUpdate"]));
            }
            set {
                this["EditUseOptimisticUpdate"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalSqlQueriesPreviewQueries {
            get {
                return ((bool)(this["GlobalSqlQueriesPreviewQueries"]));
            }
            set {
                this["GlobalSqlQueriesPreviewQueries"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalSqlQueriesShowQueriesWithResults {
            get {
                return ((bool)(this["GlobalSqlQueriesShowQueriesWithResults"]));
            }
            set {
                this["GlobalSqlQueriesShowQueriesWithResults"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Import)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImportCreateExcelTable {
            get {
                return ((bool)(this["ImportCreateExcelTable"]));
            }
            set {
                this["ImportCreateExcelTable"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Import)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MySqlDefault")]
        public string ImportExcelTableStyleName {
            get {
                return ((string)(this["ImportExcelTableStyleName"]));
            }
            set {
                this["ImportExcelTableStyleName"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditSessionsRestoreWhenOpeningWorkbook {
            get {
                return ((bool)(this["EditSessionsRestoreWhenOpeningWorkbook"]));
            }
            set {
                this["EditSessionsRestoreWhenOpeningWorkbook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<MySQL.ForExcel.Classes.EditSessionInfo> EditSessionsList {
            get {
                return ((global::System.Collections.Generic.List<MySQL.ForExcel.Classes.EditSessionInfo>)(this["EditSessionsList"]));
            }
            set {
                this["EditSessionsList"] = value;
            }
        }

        [PropertyGroup(PropertyGroup.SettingsGroup.Global)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditSessionsReuseWorksheets {
            get {
                return ((bool)(this["EditSessionsReuseWorksheets"]));
            }
            set {
                this["EditSessionsReuseWorksheets"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Import)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportPrefixExcelTable {
            get {
                return ((bool)(this["ImportPrefixExcelTable"]));
            }
            set {
                this["ImportPrefixExcelTable"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Import)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MySQL")]
        public string ImportPrefixExcelTableText {
            get {
                return ((string)(this["ImportPrefixExcelTableText"]));
            }
            set {
                this["ImportPrefixExcelTableText"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Append)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppendSqlQueriesDisableIndexes {
            get {
                return ((bool)(this["AppendSqlQueriesDisableIndexes"]));
            }
            set {
                this["AppendSqlQueriesDisableIndexes"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportSqlQueriesCreateIndexesLast {
            get {
                return ((bool)(this["ExportSqlQueriesCreateIndexesLast"]));
            }
            set {
                this["ExportSqlQueriesCreateIndexesLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideLocalizedDateFormatNames {
            get {
                return ((bool)(this["HideLocalizedDateFormatNames"]));
            }
            set {
                this["HideLocalizedDateFormatNames"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<MySQL.ForExcel.Classes.ImportSessionInfo> ImportSessionsList {
            get {
                return ((global::System.Collections.Generic.List<MySQL.ForExcel.Classes.ImportSessionInfo>)(this["ImportSessionsList"]));
            }
            set {
                this["ImportSessionsList"] = value;
            }
        }
        
        [PropertyGroup(PropertyGroup.SettingsGroup.Export)]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySQL.ForExcel.Classes.MySqlForExcelSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportShowAllMySqlDataTypes {
            get {
                return ((bool)(this["ExportShowAllMySqlDataTypes"]));
            }
            set {
                this["ExportShowAllMySqlDataTypes"] = value;
            }
        }
    }
}
